# Generated by Django 4.2.6 on 2023-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_client_photo_alter_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='desc',
            field=models.TextField(max_length=400, verbose_name='Описание клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(upload_to='clients/photo', verbose_name='Фото клиента'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/logo/', verbose_name='Лого партнера'),
        ),
    ]
